name: Go package

on: [push, pull_request]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: "Testing"
        run: "go test ./..."

      - name: "Vetting"
        run: "go vet ./..."

      - name: "StaticCheck"
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.os }}

      - name: "Build"
        run: go build -v ./...
